CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Custommer (
    cID INTEGER PRIMARY KEY AUTO_INCREMENT,
    cName VARCHAR(255) NOT NULL,
    cAge INTEGER NOT NULL
);
CREATE TABLE `Order` (
    oID INTEGER PRIMARY KEY AUTO_INCREMENT,
    cID INTEGER NOT NULL ,
    oDate DATE,
    oTotalPrice DECIMAL,
    FOREIGN KEY (cID) REFERENCES Custommer (cID)
);
CREATE TABLE Product (
    pID INTEGER PRIMARY KEY AUTO_INCREMENT,
    pName VARCHAR(255) NOT NULL,
    pPrice DECIMAL
);
CREATE TABLE OrderDetail (
    oID INT NOT NULL,
    pID INT NOT NULL,
    odQTY INT NOT NULL,
    FOREIGN KEY (oID) REFERENCES `Order` (oID),
    FOREIGN KEY (pID) REFERENCES Product (pID),
    PRIMARY KEY (oID,pID)
);